return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "bash",
      "css",
      "diff",
      "html",
      "gitignore",
      "graphql",
      "javascript",
      "jsdoc",
      "json",
      "json5",
      "jsdoc",
      "lua",
      "luadoc",
      "php",
      "scss",
      "tsx",
      "typescript",
      "vim",
      "vimdoc",
      "yaml",
    },
  },
}
