# Default colors
[colors.primary]
background = '#201f22'
foreground = '#fbf1c7'

# Normal colors
[colors.normal]
black   = '#073642'
red     = '#dc322f'
green   = '#e0af68'
yellow  = '#b58900'
blue    = '#268bd2'
magenta = '#ff4c4c'
cyan    = '#2aa198'
white   = '#eee8d5'

# Bright colors
[colors.bright]
black   = '#4c4c4c'
red     = '#cb4b16'
green   = '#586e75'
yellow  = '#657b83'
blue    = '#839496'
magenta = '#6c71c4'
cyan    = '#93a1a1'
white   = '#fdf6e3'
